config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
      resources :posts do
        resources :likes, only: %i[create destroy], shallow: true
        resources :comments, only: %i[create edit update destroy], shallow: true
      end
      resources :stories, only: %i[index new create show destroy]
      resources :users, only: %i[index show] do
        member do
          post :follow
          post :unfollow
          post :accept_request
          get :followers
          get :followeds
        end
      end
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :set_like, only: [:destroy]

  def create
    @like = current_user.likes.new(like_params)
    authorize @like
    if @like.save
      respond_to do |format|
        format.js
      end
    else
      flash.alert = 'Something went wrong.'
    end
  end

  def destroy
    authorize @like
    if @like.destroy
      respond_to do |format|
        format.js
      end
    else
      flash.alert = 'Something went wrong.'
    end
  end

  private

  def like_params
    params.permit :post_id
  end

  def set_like
    @like = Like.find(params[:id])
  end
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
  def create_like
    Like.new
  end
end

app/views/likes/_post_likes.html.erb
<div>
  <% if post.likes.find_by(user_id: current_user.id).nil? %>
    <%= link_to post_likes_path(post), method: :post, class:'btn btn-light', remote: true do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-heart" viewBox="0 0 16 16">
        <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
      </svg><br/>
    <%end%>
      <%= post.likes.size %> likes
  <% else %>
    <% like = Like.find_by(post_id: post.id, user_id: current_user.id)%>
    <%= link_to like_path(like.id), method: :delete, remote: true, class:'btn btn-light' do %>
      <svg xmlns='http://www.w3.org/2000/svg' width='32' height='32' fill='currentColor' class='bi bi-heart-fill' viewBox='0 0 16 16'>
        <path fill-rule='evenodd' d='M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z'/>
      </svg>
    <%end%><br />
    <%= post.likes.size %> likes
  <%end%>
</div>

app/views/likes/create.js.erb
$('#like-or-unlike-<%= @like.post.id.to_s %>').html("<%= j(render partial: 'likes/post_likes', locals:{ post: @like.post }) %>");

app/views/likes/destroy.js.erb
$('#like-or-unlike-<%= @like.post.id.to_s %>').html("<%= j(render partial: 'likes/post_likes', locals:{ post: @like.post }) %>");