config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
      resources :posts do
        resources :likes, only: %i[create destroy], shallow: true
        resources :comments, only: %i[create edit update destroy], shallow: true
      end
      resources :stories, only: %i[index new create show destroy]
      resources :users, only: %i[index show] do
        member do
          post :follow
          post :unfollow
          post :accept_request
          get :followers
          get :followeds
        end
      end
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  include PgSearch::Model

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :stories, dependent: :destroy
  has_one_attached :profile_picture

  has_many :followeds, class_name: 'UserFollower', foreign_key: 'follower_id', dependent: :destroy

  has_many :followers, class_name: 'UserFollower', foreign_key: 'followed_id', dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :user_name, presence: true, length: { maximum: 100 }
  validates :password, presence: true, on: :create
  validates :password, confirmation: true
  validates :email, presence: true
  validates :profile_picture, content_type: { in: ['image/png', 'image/gif', 'image/jpg', 'image/jpeg'], message: 'Upload Image only.' }
  validates :bio, length: { maximum: 100 }

  after_create :welcome_email

  pg_search_scope :search, against: :user_name, using: { trigram: { word_similarity: true, threshold: 0.1 } }

  def welcome_email
    UserMailer.welcome_email(self).deliver!
  end

  def accepted_followeds
    followeds.where(accepted: true).pluck(:followed_id)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show; end

  def follow
    user = User.find(params[:id])
    if user.account_type_private
      byebug
      if current_user.followeds.create(followed_id: params[:followed_id], accepted: false)
        byebug
        respond_to do |format|
          format.js
        end
      end
    elsif current_user.followeds.create(followed_id: params[:followed_id], accepted: true)
      respond_to do |format|
        format.js
      end
    end
  end

  def index
    @users = User.search(params[:term])
    respond_to do |format|
      format.js
    end
  end

  def unfollow
    if current_user.followeds.find_by(followed_id: params[:id]).destroy
      respond_to do |format|
        format.js
      end
    else
      flash.alert = 'Unable to unfollow'
      format.js
    end
  end

  def accept_request
    request = UserFollower.find_by(follower_id: params[:follower_id])
    ActiveRecord::Base.transaction do
      if request.update!(accepted: true)
        respond_to do |format|
          format.js
        end
      else
        flash.alert = 'Something went wrong.'
        format.js
      end
    rescue ActiveRecord::Exception
      flash.alert = 'Something went wrong.'
      redirect_to(:back)
    end
  end

  def followers; end

  def followeds; end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  def follow_suggestions
    User.where.not(id: current_user.followeds.pluck(:followed_id) << current_user.id)
  end

  def follow_requests
    UserFollower.where(followed_id: current_user.id, accepted: false)
  end

  def followers
    UserFollower.where(followed_id: current_user.id, accepted: true)
  end

  def followeds
    UserFollower.where(follower_id: current_user.id, accepted: true)
  end
end

app/views/users/_following.html.erb
<div class='container mt-5'>
  <div class="d-flex justify-content-center row">
    <div class="col-md-6">
      <div class="p-3 bg-white text-center">
        <div>
          Your are Following
        </div>
        <% followeds.each do |followed| %>
          <div class="d-flex flex-row justify-content-between align-items-center">
            <div class="d-flex flex-row align-items-center">
              <%= render 'shared/profile_picture', profile_picture: followed.followed.profile_picture%>
              <div class="d-flex flex-column align-items-start ml-2">
                <span class="font-weight-bold"><%= link_to followed.followed.user_name, user_path(followed.followed.id), class:'profile-path'%>
                </span>
              </div>
            </div>
            <div class="d-flex flex-row align-items-center mt-2">
              <%= form_tag(unfollow_user_path(followed.followed.id), method: :post, remote: true) do %>
                <%= hidden_field_tag :followed_id, followed.followed.id %>
                <%= submit_tag "UnFollow", class: "btn btn-info"%>
              <%end%>
            </div>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/users/_users_result.html.erb
<% if @users.present? %>
  <% @users.each do |user| %>
    <%= link_to user_path(user.id), class: "no-text-decoration normal-color" do %>
      <div class="search-result-item"><%= user.user_name %></div>
    <% end %>
  <% end %>
<% else %>
  <div class="p-3">
    No results found.
  </div>
<% end %>

app/views/users/accept_request.js.erb
$('#follows-requests').html("<%= j render 'shared/follow_requests', collection: follow_requests%>");
$('#follower-suggestions').html("<%= j render 'shared/followers_suggestion', collection: follow_suggestions%>");

app/views/users/follow.js.erb
$('#follower-suggestions').html("<%= j render 'shared/followers_suggestion', collection: follow_suggestions%>");

app/views/users/follow_user.js.erb
<% @follower_suggestions = User.where.not id: current_user.followeds.map{ |f| f['user_id'] } << current_user.id %>
$('#follower-suggestions').html("<%= j render 'shared/followers_suggestion', collection: @follower_suggestions%>");

app/views/users/followeds.html.erb
<div id='flash-message'>
  <%= render 'shared/flashmessage' %>
</div>
<div id='followeds'>
  <%= render 'following' %>
</div>

app/views/users/followers.html.erb
<%= render 'shared/flashmessage' %>
<% followers.each do |follower| %>
  <div class='container mt-5'>
    <div class="d-flex justify-content-center row">
      <div class="col-md-6">
        <div class="p-3 bg-white text-center">
          <div>
            Your Followers
          </div>
          <div class="d-flex flex-row justify-content-between align-items-center">
            <div class="d-flex flex-row align-items-center">
              <%= render 'shared/profile_picture', profile_picture: follower.follower.profile_picture%>
              <div class="d-flex flex-column align-items-start ms-2">
                <span class="font-weight-bold"><%= link_to follower.follower.user_name, user_path(follower.follower.id), class:'profile-path'%>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/users/index.js.erb
$('#users-result').html("<%= j render 'users_result', collection: @users%>");

app/views/users/profile.html.erb
<div class='container top-margin'>
  <div class='row'>
    <div class='col-4'>
      <% if @user.profile_picture.attached? %>
        <%= image_tag @user.profile_picture, class: 'profile-pic'%>
      <% else %>
        <%= image_tag 'default_dp.jpg', width: '50px', height: '50px', class: 'profile-pic'%>
      <%end%>
    </div>
    <div class='col-8 text-left'>
      <h1><%= @user.user_name%></h1>
      <%= link_to 'Edit Profile', edit_user_registration_path, class:'btn btn-secondary profile-path'%>
      <div class='profile-stats'>
        <%= @user.posts.count %> posts
      </div>
      <div class='profile-stats'>
        <%= @user.followers.count %> followers
      </div>
      <div class='profile-stats'>
        <%= @user.followeds.count %> following
      </div>
      <br /><%= @user.bio%>
    </div>
  </div>
  <div class='row'>
    <% @user.posts.each do |post| %>
      <div class='col-4'>
        <div class='d-flex flex-row justify-content-center'>
          <% post.images.each do |image|%>
            <%= image_tag image, class: 'mt-5 p-5'%>
          <%end%>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/users/show.html.erb
<div class='container top-margin'>
  <div class='row'>
    <div class='col-4'>
      <% if @user.profile_picture.attached? %>
        <%= image_tag @user.profile_picture, class: 'profile-picture'%>
      <%end%>
    </div>
    <div class='col-8 text-left mt-5'>
      <h1><%= @user.user_name%></h1>
      <%if @user.id == current_user.id %>
        <%= link_to 'Edit Profile', edit_user_registration_path, class:'btn btn-secondary profile-path'%>
      <%end%>
      <div class='profile-stats'>
        <%= @user.posts.count %> posts
      </div>
      <div class='profile-stats'>
        <a href='<%= followers_user_path(current_user)%>' class='text-reset'> <%= @user.followers.where(accepted: true).count %> followers</a>
      </div>
      <div class='profile-stats'>
        <a href='<%= followeds_user_path(current_user)%>' class='text-reset'> <%= @user.followeds.where(accepted: true).count %> following</a>
      </div>
      <br /><%= @user.bio%>
    </div>
  </div>
  <div class='row'>
    <div class='col-md-12'>
      <% @user.posts.each do |post| %>
        <% if policy(post).show? %>
          <div class='d-flex flex-row justify-content-start'>
            <% post.images.each do |image|%>
              <a href='<%= post_path(post)%>'><%= image_tag image, class: 'mx-auto p-5 img-stack'%></a>
            <%end%>
          </div>
        <%end%>
      <%end%>
    </div>
  </div>
</div>

app/views/users/unfollow.js.erb
$('#followeds').html("<%= j render 'users/following', collection: followeds%>");
$('#flash-message').html("<%= j render 'shared/flashmessage', collection: followeds%>");

app/views/users/unfollow_user.js.erb
<% @follower_suggestions = User.where.not id: current_user.followeds.map{ |f| f['user_id'] } << current_user.id %>
$('#follower-suggestions').html("<%= j render 'shared/followers_suggestion', collection: @follower_suggestions%>");