config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
      resources :posts do
        resources :likes, only: %i[create destroy], shallow: true
        resources :comments, only: %i[create edit update destroy], shallow: true
      end
      resources :stories, only: %i[index new create show destroy]
      resources :users, only: %i[index show] do
        member do
          post :follow
          post :unfollow
          post :accept_request
          get :followers
          get :followeds
        end
      end
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashmessage.html.erb
<% flash.each do |type, msg|%>
  <div id='flashmessage' class='alert alert-info'>
    <%= msg%>
  </div>
<%end%>

app/views/shared/_follow_requests.html.erb
<% follow_requests.each do |request| %>
  <div class='recommended-follower'>
    <div class='row'>
      <div class='col-sm-3 col-lg-2'>
        <%= render 'shared/profile_picture', profile_picture: request.follower.profile_picture%>
      </div>
      <div class='col-sm-9 col-lg-10'>
        <%= link_to request.follower.user_name, user_path(request.follower.id), class:'profile-path'%>
        <div class='float-end'>
          <%= form_tag(accept_request_user_path(request.follower_id), method: :post, remote: true) do %>
            <%= hidden_field_tag :follower_id, request.follower_id %>
            <%= submit_tag "Accept", class: "btn btn-info"%>
          <%end%>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/shared/_followers_suggestion.html.erb
<% follow_suggestions.each do |user| %>
  <div class='recommended-follower'>
    <div class='row'>
      <div class='col-sm-3 col-lg-2'>
        <%= render 'shared/profile_picture', profile_picture: user.profile_picture%>
      </div>
      <div class='col-sm-9 col-lg-10'>
        <%= link_to user.user_name, user_path(user.id), class:'profile-path'%>
        <div class='float-end'>
          <%= form_tag(follow_user_path(user.id), method: :post, id: 'follow_form', remote: true) do %>
            <%= hidden_field_tag :followed_id, user.id %>
            <%= submit_tag "Follow", class: "btn btn-info"%>
          <%end%>
        </div>
      </div>
    </div>
  </div>
<%end%>

app/views/shared/_navbar.html.erb
<div class='navigation'>
  <div class='logo'>
    <%= link_to authenticated_root_path do%>
      <%= image_tag 'Instagram-Logo.png', class: 'logo-img' %>
    <% end %>
  </div>
  <div class='navigation-search-container'>
    <%= form_tag users_path, method: :get, class: "form-inline my-2 my-lg-0 ml-md-auto", id: "users-search", remote: true do %>
      <%= text_field_tag :term, params[:term], class: "form-control mr-sm-2 text-center common-btn", placeholder: "Search", autocomplete: "off" %>
      <div id="users-result"></div>
    <% end %>
  </div>
  <div class='navigation-icons'>
    <div class='navigation-link'>
      <%= link_to 'New Post', new_post_path %>
    </div>
    <div class='navigation-link' style='margin-left: 10px;'>
      <%= link_to 'Add Story', new_story_path %>
    </div>
    <div class='navigation-link' style='margin-left: 10px;'>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
    </div>
  </div>
</div>

app/views/shared/_profile_picture.html.erb
<% if profile_picture.attached? %>
  <%= image_tag profile_picture, class: 'profile-pic p-2'%>
<% else %>
  <%= image_tag 'default_dp.jpg', class: 'profile-pic'%>
<%end%>

app/views/shared/_show_all_posts.html.erb
<% posts.each do |post|%>
  <div class='mt-5 bg-white'>
    <div class='post-meta'>
      <%= render 'shared/profile_picture', profile_picture: post.user.profile_picture%>
      <%= link_to post.user.user_name, user_path(post.user.id), class:'profile-path'%>
    </div>
    <% if policy(post).update? && policy(post).destroy?%>
      <%= link_to edit_post_path(post.id), class: 'p-2' do %>
        <%= fa_icon 'edit 2x muted'%>
      <%end%>
      <%= link_to  post_path(post.id), class: 'p-2', method: :delete, data: { confirm: 'Are you sure?' } do %>
        <%= fa_icon 'trash 2x muted'%>
      <%end%>
    <%end%>
    <div class='post-details'>
      <%= link_to post.description, post_path(post), class:'profile-path'%>
    </div>
    <% if !post.images.nil? %>
      <% post.images.each_with_index do |image, i|%>
        <div class="owl-carousel">
          <div>
            <%= cl_image_tag(image.key, class:'post-image') %>
          </div>
        </div>
      <%end%>
    <%end%>
    <p class='text-muted'><%= time_ago_in_words post.created_at %> ago</p>
    <div id='like-or-unlike-<%= post.id.to_s %>'>
      <%= render 'likes/post_likes', post: post%>
    </div>
    <div id="comment-form-post-<%= post.id.to_s %>" class='comment-form'>
      <%= render 'comments/comment_form', post: post%>
    </div>
    <div id="comment-post-<%= post.id.to_s %>" class='comments'>
      <%= render 'posts/show_comments', post: post %>
    </div>
  </div>
<%end%>
<%= paginate posts, class: 'p-2'%>

app/views/shared/_stories.html.erb
<small><%= link_to 'See all', stories_path, class:'top-margin'%></small>
<div class='stories-block'>
  <% stories.each do |story| %>
    <div class='col-md-1'>
    <%= link_to story_path(story.id) do %>
      <% if story.user.profile_picture.attached? %>
        <%= image_tag story.user.profile_picture, class: 'profile-pic' %>
      <% else %>
        <%= image_tag 'default_dp.jpg', class: 'profile-pic'%>
      <%end%>
    <%end%>
      <%= link_to story.user.user_name, story_path(story.id), class:'profile-path'%>
    </div>
  <%end%>
</div>