config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
      resources :posts do
        resources :likes, only: %i[create destroy], shallow: true
        resources :comments, only: %i[create edit update destroy], shallow: true
      end
      resources :stories, only: %i[index new create show destroy]
      resources :users, only: %i[index show] do
        member do
          post :follow
          post :unfollow
          post :accept_request
          get :followers
          get :followeds
        end
      end
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many_attached :images

  validates :description, presence: true, length: { maximum: 1000 }
  validates :images, content_type: { in: ['image/png', 'image/gif', 'image/jpg', 'image/jpeg'], message: 'Upload Image only.' }
  validate :number_of_images

  private

  def number_of_images
    errors[:base] << "Post can't contain more than 10 image." if images.length > 10
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :can_authorize, only: %i[show edit update destroy]

  def index
    @posts = posts.order('created_at DESC').page(params[:page]).per(6)
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    @post = current_user.posts.new(post_params)
    authorize @post
    if @post.save
      flash.alert = 'Post created successfully.'
      redirect_to authenticated_root_path
    else
      flash.alert = 'Error in creating Post'
      render 'new'
    end
  end

  def show; end

  def edit
    byebug
  end

  def update
    @image = @post.images.where(id: params[:image_id])
    if @image.present?
      @post.images.find(params[:image_id]).purge
      redirect_back(fallback_location: edit_post_path)
    else
      if @post.update(post_params)
        flash.alert = 'Post updated successfully.'
        redirect_to authenticated_root_path
      else
        flash.alert = 'Error in updating post'
        render 'edit'
      end
    end
  end

  def destroy
    flash.alert = if @post.destroy
                    'Post deleted successfully.'
                  else
                    'Error in deleting.'
                  end
    redirect_to authenticated_root_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def can_authorize
    authorize @post
  end

  def post_params
    params.require(:post).permit(:description, images: [])
  end

  def posts
    @posts = Post.includes([:comments, :likes]).where(user_id: current_user.accepted_followeds << current_user.id)
  end
end

app/helpers/post_helper.rb
# frozen_string_literal: true

module PostHelper
end

app/views/posts/_show_all_posts.html.erb
<% posts.each do |post|%>
  <div class='mt-5 bg-white'>
    <div class='post-meta'>
      <%= render 'shared/profile_picture', profile_picture: post.user.profile_picture%>
      <%= link_to post.user.user_name, user_path(post.user.id), class:'profile-path'%>
    </div>
    <% if policy(post).update? && policy(post).destroy?%>
      <%= link_to edit_post_path(post.id), class: 'p-2' do %>
        <%= fa_icon 'edit 2x muted'%>
      <%end%>
      <%= link_to  post_path(post.id), class: 'p-2', method: :delete, data: { confirm: 'Are you sure?' } do %>
        <%= fa_icon 'trash 2x muted'%>
      <%end%>
    <%end%>
    <div class='post-details'>
      <%= link_to post.description, post_path(post), class:'profile-path'%>
    </div>
    <div id='carouselExampleSlidesOnly' class='carousel slide' data-bs-ride='carousel'>
      <div class='carousel-inner'>
        <% post.images.each_with_index do |image, i|%>
          <div class='carousel-item <%= 'active ' if i == 0 %> '>
            <div class='imageContainer'>
              <%= image_tag(image, class:'post-image')%>
            </div>
          </div>
          <%end%>
      </div>
      <button class='carousel-control-prev' type='button' data-bs-target='#carouselExampleControls' data-bs-slide='prev'>
        <span class='carousel-control-prev-icon' aria-hidden='true'></span>
        <span class='visually-hidden'>Previous</span>
      </button>
      <button class='carousel-control-next' type='button' data-bs-target='#carouselExampleControls' data-bs-slide='next'>
        <span class='carousel-control-next-icon' aria-hidden='true'></span>
        <span class='visually-hidden'>Next</span>
      </button>
    </div>
    <p class='text-muted'><%= time_ago_in_words post.created_at %> ago</p>
    <div id='like-or-unlike-<%= post.id.to_s %>'>
      <%= render 'likes/post_likes', post: post%>
    </div>
    <div id="comment-form-post-<%= post.id.to_s %>" class='comment-form'>
      <%= render 'comments/comment_form', post: post%>
    </div>
    <div id="comment-post-<%= post.id.to_s %>" class='comments'>
      <%= render 'posts/show_comments', post: post %>
    </div>
  </div>
<%end%>
<%= paginate posts, class: 'p-2'%>

app/views/posts/_show_comments.html.erb
<div class='page-header'>
  <small class='m-1'><%= post.comments.size %> comments</small>
</div>
<div class='comments-list'>
  <% post.comments.each do |comment|%>
    <div class='comments-field'>
      <div class='d-flex justify-content-start'>
        <h5 class='font-weight-bold mt-2'><%= comment.user.user_name%></h5>
      </div>
      <div id='show-<%=comment.id.to_s%>'>
        <%= comment.content %>
        <% if policy(comment).update?%>
          <div class='pull-right'>
            <%= link_to edit_comment_path(comment), remote: true, class: 'm-2' do%>
              <%= fa_icon 'edit muted'%>
            <%end%>
          </div>
        <%end%>
        <%if policy(comment).destroy?%>
          <div class='pull-right'>
            <%= link_to comment_path(comment), remote: true, class: 'm-2', method: :delete, data: { confirm: 'Are you sure?' } do %>
              <%= fa_icon 'trash muted'%>
            <%end%>
          </div>
        <% end %>
      </div>
      <div id='edit-<%=comment.id.to_s%>' class="d-none">
        <%= render 'comments/edit', comment: comment%>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/_stories.html.erb
<small><%= link_to 'See all', stories_path, class:'top-margin'%></small>
<div class='stories-block'>
  <% stories.each do |story| %>
    <div class='col-md-1 ms-2'>
      <%= link_to story_path(story.id) do %>
        <%= render 'shared/profile_picture', profile_picture: story.user.profile_picture %>
      <%end%>
        <%= link_to story.user.user_name, story_path(story.id), class:'profile-path'%>
      </div>
  <%end%>
</div>

app/views/posts/edit.html.erb
<div class='container top-margin'>
  <%= render 'shared/flashmessage' %>
  <%= form_with model: @post do |form|%>
    <div class='form-group'>
      <%= form.label :description %><br>
      <%= form.text_field :description, class: 'form-control', required: true, minlength: "5" %>
    </div>
    <div class='form-group'>
      <%= form.label :images%>
      <%= form.file_field :images, multiple: true, accept:'image/png, image/gif, image/jpeg, image/jpg', id: 'images-count', class: 'form-control', data: { images_count: @post.images.count }%>
    </div>
    <div class='form-group'>
      <%= form.submit class: 'btn btn-success' %>
    </div>
  <% end%>
  <div class='cards'>
    <% @post.images.each do |image|%>
      <div class='card'>
        <%= image_tag image %>
        <%= button_to 'Delete Image', { action: 'update', image_id: image.id },
          method: :patch, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
      </div>
    <%end%>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'shared/flashmessage' %>
    <div class="col-md-8 mt-5 mb-3">
      <% if stories.count > 0%>
        <%= render 'stories' %><br />
      <%end%>
      <%= render 'show_all_posts', posts: @posts%>
    </div>
    <div class="col-md-4">
      <div class='account-summary'>
        <%= render 'shared/profile_picture', profile_picture: current_user.profile_picture%>
        <%= link_to current_user.user_name, user_path(current_user.id), class:'profile-path'%>
      </div>
      <%if follow_suggestions.count > 0%>
        <div id='follower-suggestions' class='follower-suggestions' >
          <p class='text-muted'>Suggestionsfor you</p>
          <%= render 'shared/followers_suggestion' %>
        </div>
      <%end%>
      <% if follow_requests.count > 0 %>
        <div id='follows-requests' class='follower-suggestions'>
          <p class='text-muted'>Follow requests</p>
          <%= render 'shared/follow_requests'%>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class='container top-margin'>
  <%= render 'shared/flashmessage' %>
  <%= form_with model: @post, local: true do |form|%>
    <div class='form-group'>
      <%= form.label :description %><br>
      <%= form.text_area :description, class: 'form-control', required: true, minlength: "5"%><br />
    </div>

    <div class='form-group'>
      <%= form.label :images%>
      <%= form.file_field :images, multiple: true, required: true, accept:'image/png, image/gif, image/jpeg, image/jpg', id: 'images-count', class: 'form-control', data: { images_count: @post.images.count }%><br />
    </div>

    <div class='form-group'>
      <%= form.submit "Create", class: 'btn btn-success' %>
    </div>
  <% end%>
</div>

app/views/posts/show.html.erb
<div class='container mt-5 mb-5'>
  <%= render 'shared/flashmessage' %>
  <div class='d-flex justify-content-start m-2'>
    <%= render 'shared/profile_picture', profile_picture: @post.user.profile_picture%>
    <h5 class='ms-2 mt-2'><%= @post.user.user_name%></h5><br/>
  </div>
  <% if policy(@post).update? && policy(@post).destroy?%>
    <%= link_to edit_post_path(@post.id), class: 'p-2' do %>
      <%= fa_icon 'edit 2x muted'%>
    <%end%>
    <%= link_to  post_path(@post.id), class: 'p-2', method: :delete, data: { confirm: 'Are you sure?' } do %>
      <%= fa_icon 'trash 2x muted'%>
    <%end%>
  <%end%>
  <p><%= @post.description%></p>

  <div id='carouselExampleSlidesOnly' class='carousel slide' data-bs-ride='carousel'>
    <div class='carousel-inner'>
      <% @post.images.each_with_index do |image, i|%>
        <div class='carousel-item <%= 'active ' if i == 0 %> '>
          <div class='imageContainer'>
            <%= image_tag(image, class:'post-image')%>
          </div>
        </div>
        <%end%>
    </div>
    <button class='carousel-control-prev' type='button' data-bs-target='#carouselExampleControls' data-bs-slide='prev'>
      <span class='carousel-control-prev-icon' aria-hidden='true'></span>
      <span class='visually-hidden'>Previous</span>
    </button>
    <button class='carousel-control-next' type='button' data-bs-target='#carouselExampleControls' data-bs-slide='next'>
      <span class='carousel-control-next-icon' aria-hidden='true'></span>
      <span class='visually-hidden'>Next</span>
    </button>
  </div>
  <div id='like-or-unlike-<%= @post.id.to_s %>' >
    <%= render 'likes/post_likes', post: @post%>
  </div>
  <div id="comment-form-post-<%= @post.id.to_s %>" class='col-8 comment-form'>
    <%= render 'comments/comment_form', post: @post%>
  </div>
  <div id="comment-post-<%= @post.id.to_s %>" class='col-8 comments'>
    <%= render 'posts/show_comments', post: @post %>
  </div>
</div>